### ISSUE TITLE
BUG youtube videos

### ISSUE THREAD

**Issue by FabioS82** [llomgui/OceanProject-Bot#45]
the bot does not send links to the room even with the button !say it does not send url

**Comment by llomgui** [comment]
Hey,

Did  you try to promote your bot to member?

**Comment by FabioS82** [comment]
Good morning, I'm not able to verify this because of me this error when connecting

PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/fabio/Desktop/Novo/OceanProject-Bot-master/modules/onChatInfo.php:16
Stack trace:
#0 /home/fabio/Desktop/Novo/OceanProject-Bot-master/dev.php(287): {closure}(Array)
#1 /home/fabio/Desktop/Novo/OceanProject-Bot-master/dev.php(250): dispatch('modules', 'onChatInfo', Array)
#2 {main}
  thrown in /home/fabio/Desktop/Novo/OceanProject-Bot-master/modules/onChatInfo.php on line 16

**Comment by Tehchy** [comment]
fixed in my latest pr

**Comment by FabioS82** [comment]
Thanks, apparently youtube was not a member. And another bug has been fixed by the Tehchy
