### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by skyleter** [llomgui/OceanProject-Bot#48]
PHP Parse error:  syntax error, unexpected '$stream' (T_VARIABLE) in /root/xat/classes/xatNetwork.php on line 242

Lol.  Not sure why. Just tried on my linux vps with php7...

**Comment by skyleter** [comment]
Okay, got it...

```
    `$stream = [] `<--- Missing semicolon at line 241 @llomgui 
```

**Comment by skyleter** [comment]
@llomgui

**Comment by Tehchy** [comment]
i forgot to pr the fix LOL
