### ISSUE TITLE
Autowelcome, automember and responses could be added.

### ISSUE THREAD

**Issue by grimacecoin** [llomgui/OceanProject-Bot#60]
They could add the autowelcome and automember also the answers, I have the functions and the command but not add it, you could give them to add it or make your own.

**Comment by llomgui** [comment]
I added both functions.

What do you mean by "the answers"?

**Comment by grimacecoin** [comment]
I refer to this example:

Hi - I say hello

Hello welcome - The bot says hello

I would like to know if I can help with this project, I am not a programmer and none of that but I could help in what I can, I know little of PHP but I could try to create commands and upload it, if you want to clear there are already 5 programmers and not I think you want but I just want to help.

**Comment by llomgui** [comment]
You mean responses.

Of course you can help, that's why this project is on github.

**Comment by grimacecoin** [comment]
If the responses

OK thanks, :)

**Comment by llomgui** [comment]
Responses added.
